version: "3.9"

services:
  # -------------------- ZOOKEEPER --------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spark-network

  # -------------------- KAFKA --------------------
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spark-network

  # -------------------- CASSANDRA --------------------
  cassandra-db:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
    volumes:
      - ./cassandra_data:/var/lib/cassandra:cached
    networks:
      - spark-network

  # -------------------- JUPYTER NOTEBOOK + SPARK --------------------
  jupyter-spark:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter-spark
    ports:
      - "8890:8888"
      - "8080:8080"  # Spark Master UI
      - "8081:8081"  # Spark Worker UI
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./spark_jars:/usr/local/spark/jars
    environment:
      - SPARK_MASTER=spark://jupyter-spark:7077
      - PYSPARK_PYTHON=python3
    command: >
      start-notebook.sh
      --NotebookApp.token=''
      --NotebookApp.password=''
      --NotebookApp.allow_origin='*'
      --NotebookApp.ip='0.0.0.0'
      --NotebookApp.disable_check_xsrf=True
    networks:
      - spark-network
    depends_on:
      - kafka
      - cassandra-db

networks:
  spark-network:
    name: spark-network
